### ISSUE TITLE
Should be a `refreshToken`

### ISSUE THREAD

**Issue by talkenson** [foxy-core/foxy-spa#2]
https://github.com/foxy-core/foxy-spa/blob/ffacfd77fc4a3b0d18dba95e376af0fa0b5f1ab9/src/_app/use-cases/auth/refresh.ts#L36

**Comment by roamiiing** [comment]
Also, `exists` call should be omitted here
https://github.com/foxy-core/foxy-spa/blob/ffacfd77fc4a3b0d18dba95e376af0fa0b5f1ab9/src/_app/use-cases/auth/refresh.ts#L32
